<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
</PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\GDIIECA.Application\GDIIECA.Application.csproj" />
    <ProjectReference Include="..\GDIIECA.Domain\GDIIECA.Domain.csproj" />
    <FrameworkReference Include="Microsoft.AspNetCore.App" />
    <PackageReference Include="Microsoft.AspNetCore.Identity.EntityFrameworkCore" Version="8.0.29" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.SqlServer" Version="8.0.29" />
  </ItemGroup>

</Project>
