using GDIIECA.Application.Common;
using GDIIECA.Application.DTOs;
using GDIIECA.Domain.Enums;

namespace GDIIECA.Application.Interfaces;

public interface IAreaService { Task<IReadOnlyList<AreaDto>> ListAsync(CancellationToken ct = default); Task<Guid> SaveAsync(AreaDto item, string userId, CancellationToken ct = default); }
public interface IProcessService { Task<IReadOnlyList<ProcessDto>> ListAsync(CancellationToken ct = default); Task<Guid> SaveAsync(ProcessDto item, string userId, CancellationToken ct = default); }
public interface IFolderService { Task<IReadOnlyList<FolderDto>> ListAsync(CancellationToken ct = default); Task<IReadOnlyList<BreadcrumbDto>> BreadcrumbsAsync(Guid id, CancellationToken ct = default); Task<Guid> CreateAsync(string name, Guid? parentId, Guid? areaId, Guid? processId, string userId, CancellationToken ct = default); Task MoveAsync(Guid id, Guid? parentId, string userId, CancellationToken ct = default); Task DeleteAsync(Guid id, string userId, CancellationToken ct = default); Task RestoreAsync(Guid id, string userId, CancellationToken ct = default); }
public interface IDocumentService { Task<IReadOnlyList<DocumentDto>> ListAsync(Guid? folderId, string? query, CancellationToken ct = default); Task<DocumentDto?> GetAsync(Guid id, CancellationToken ct = default); Task<Guid> CreateAsync(string name, string? description, Guid folderId, Stream content, string fileName, string mimeType, string? comment, string userId, CancellationToken ct = default); Task RenameAsync(Guid id, string name, string userId, CancellationToken ct = default); Task AddVersionAsync(Guid documentId, Stream content, string fileName, string mimeType, string? comment, string userId, CancellationToken ct = default); Task<IReadOnlyList<DocumentVersionDto>> VersionsAsync(Guid documentId, CancellationToken ct = default); Task<(Stream Content, string FileName, string MimeType)> OpenVersionAsync(Guid versionId, string userId, CancellationToken ct = default); Task DeleteAsync(Guid id, string userId, CancellationToken ct = default); Task RestoreAsync(Guid id, string userId, CancellationToken ct = default); }
public interface IUserService { Task<PagedResult<UserDto>> ListAsync(int page, int pageSize, CancellationToken ct = default); Task<IReadOnlyList<string>> ListRolesAsync(CancellationToken ct = default); Task<(bool Success, string? Error)> CreateAsync(CreateUserRequest request, string actorId, CancellationToken ct = default); Task SetActiveAsync(string id, bool active, string actorId, CancellationToken ct = default); Task<(bool Success, string? Error)> ResetPasswordAsync(string id, string temporaryPassword, string actorId, CancellationToken ct = default); }
public interface IPermissionService { Task<bool> HasPermissionAsync(string userId, IEnumerable<string> roles, Guid resourceId, PermissionResourceType resourceType, PermissionAction action, Guid? areaId = null, CancellationToken ct = default); }
public interface IAuditService { Task RecordAsync(string action, string entity, string? entityId, string description, string? userId, object? oldValues = null, object? newValues = null, CancellationToken ct = default); }
public interface IFileStorageService { Task<StoredFile> SaveAsync(Stream content, string originalFileName, CancellationToken ct = default); Task<Stream> OpenReadAsync(string relativePath, CancellationToken ct = default); Task DeleteAsync(string relativePath, CancellationToken ct = default); }
public sealed record StoredFile(string StoredFileName, string RelativePath, long SizeBytes, string Sha256);
